id: 38b5127721074542a1f9374368744dd9
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_78-The_Questions_of_Gunaratnasankusumita-v2
  language: bo
  author: ''
  volume: {}
